# Generated by Django 4.2.5 on 2023-09-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
