# Generated by Django 4.2.5 on 2023-10-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
